// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iwqqkpwuisbdedldianz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml3cXFrcHd1aXNiZGVkbGRpYW56Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyMjU4NTAsImV4cCI6MjA2OTgwMTg1MH0.WiRvMNcFIh1Ic50kiX3g-oBwHTTHRDmcb5UiApGv2HY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});